# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id_altas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(default='sms', max_length=20)),
                ('campania', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id_bajas', models.AutoField(primary_key=True, serialize=False)),
                ('id_club', models.IntegerField()),
                ('id_suscriptor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(default='sms', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Base_cargada_broadcast',
            fields=[
                ('id_base_cargada', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11)),
                ('fecha_envio', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Base Cargada Broadcast',
                'verbose_name': 'Base_cargada_broadcast',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_club', models.CharField(max_length=20)),
                ('corto_mo_gratis', models.CharField(max_length=6)),
                ('corto_mt_gratis', models.CharField(max_length=6)),
                ('corto_mo_cobro', models.CharField(max_length=6)),
                ('corto_mt_cobro1', models.CharField(max_length=6)),
                ('corto_mt_cobro2', models.CharField(max_length=6)),
                ('corto_mt_cobro3', models.CharField(max_length=6)),
                ('corto_broadcast', models.CharField(max_length=6)),
                ('limite_envios_broadcast', models.PositiveIntegerField()),
                ('cantidad_cobros_diarios', models.PositiveSmallIntegerField()),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_suscriptor',
            fields=[
                ('id_club_suscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_primera_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_evento', models.DateTimeField(auto_now=True)),
                ('fecha_ultimo_cobro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Club Suscriptores',
                'verbose_name': 'Club_suscriptor',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_broadcast',
            fields=[
                ('id_broadcast', models.AutoField(primary_key=True, serialize=False)),
                ('corto_envio', models.CharField(max_length=6)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('texto', models.CharField(max_length=160)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Configuración Broadcast',
                'verbose_name': 'Configuracion_broadcast',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_envio',
            fields=[
                ('id_configuracion_envio', models.AutoField(primary_key=True, serialize=False)),
                ('hora_envio', models.TimeField()),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('fecha_ultimo_envio', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Configuración Envios',
                'verbose_name': 'Configuracion_envio',
            },
        ),
        migrations.CreateModel(
            name='Configuracion_reenvio',
            fields=[
                ('id_configuracion_reenvio', models.AutoField(primary_key=True, serialize=False)),
                ('hora_envio', models.DateField()),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('fecha_ultimo_envio', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Configuración Reenvios',
                'verbose_name': 'Configuracion_reenvio',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=200)),
                ('aleatorio', models.BooleanField()),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_programado',
            fields=[
                ('id_contenido_programado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('fecha_ejecucion', models.DateTimeField()),
                ('fecha_culminacion', models.DateTimeField()),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Contenido')),
            ],
            options={
                'verbose_name_plural': 'Contenidos Programados',
                'verbose_name': 'Contenido_programado',
            },
        ),
        migrations.CreateModel(
            name='Conteo_recobro',
            fields=[
                ('id_conteo_recobro', models.AutoField(primary_key=True, serialize=False)),
                ('id_club', models.PositiveSmallIntegerField()),
                ('recobro', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Conteo Recobros',
                'verbose_name': 'Conteo_recobro',
            },
        ),
        migrations.CreateModel(
            name='Dlr',
            fields=[
                ('id_dlr', models.AutoField(primary_key=True, serialize=False)),
                ('smsc_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=20)),
                ('dlr_to', models.CharField(max_length=100)),
                ('dlr_from', models.CharField(max_length=100)),
                ('dlr_ts', models.CharField(max_length=100)),
                ('id_sms', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dlrs',
                'verbose_name': 'Dlr',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id_edge', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('dlr_mask', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=20)),
                ('dlr_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Plataforma Envio EDGE',
                'verbose_name': 'Edge',
            },
        ),
        migrations.CreateModel(
            name='Envio_contenido',
            fields=[
                ('id_envio_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('id_sms', models.CharField(blank=True, max_length=10)),
                ('cobro', models.PositiveSmallIntegerField()),
                ('msisdn', models.CharField(max_length=11)),
                ('fecha', models.DateTimeField()),
                ('corto', models.CharField(max_length=11)),
                ('recobro', models.PositiveSmallIntegerField()),
                ('id_contenido_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Contenido_programado')),
            ],
            options={
                'verbose_name_plural': 'Envio Contenidos',
                'verbose_name': 'Envio_contenido',
            },
        ),
        migrations.CreateModel(
            name='Estado_envio',
            fields=[
                ('id_estado_envio', models.AutoField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estado Envios',
                'verbose_name': 'Estado_envio',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'verbose_name': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Lista_negra',
            fields=[
                ('id_lista_negra', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11, unique=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lista Negra',
                'verbose_name': 'Lista_negra',
            },
        ),
        migrations.CreateModel(
            name='Mensajes_informativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=160)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name_plural': 'Mensajes Informativos',
                'verbose_name': 'Mensajes_informativo',
            },
        ),
        migrations.CreateModel(
            name='Mensajes_mo',
            fields=[
                ('id_mo', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=11)),
                ('destino', models.CharField(max_length=11)),
                ('mensaje', models.CharField(max_length=200)),
                ('binfo', models.CharField(max_length=6)),
                ('ruta', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mensajes Entrantes',
                'verbose_name': 'Mensajes_mo',
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id_operadora', models.AutoField(primary_key=True, serialize=False)),
                ('operadora', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20, unique=True)),
                ('codigo_pais', models.CharField(max_length=3)),
                ('codigo_area', models.CharField(max_length=3)),
                ('moneda', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Pais_operadora',
            fields=[
                ('id_pais_operadora', models.AutoField(primary_key=True, serialize=False)),
                ('id_operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Operadora')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Pais')),
            ],
            options={
                'verbose_name_plural': 'Pais-Operadora',
                'verbose_name': 'Pais_operadora',
            },
        ),
        migrations.CreateModel(
            name='Plataforma_envio',
            fields=[
                ('id_plataforma_envio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Plataforma Envio',
                'verbose_name': 'Plataforma_envio',
            },
        ),
        migrations.CreateModel(
            name='Reporte_alta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('medio', models.CharField(max_length=20)),
                ('campania', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Reporte Altas',
                'verbose_name': 'Reporte_alta',
            },
        ),
        migrations.CreateModel(
            name='Reporte_baja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('medio', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Reporte Bajas',
                'verbose_name': 'Reporte_baja',
            },
        ),
        migrations.CreateModel(
            name='Reporte_base_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('operadora', models.CharField(max_length=15)),
                ('usuarios_activos', models.IntegerField()),
                ('usuarios_baja', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Reporte Base Total',
                'verbose_name': 'Reporte_base_total',
            },
        ),
        migrations.CreateModel(
            name='Reporte_cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('medio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Reporte Cobros',
                'verbose_name': 'Reporte_cobro',
            },
        ),
        migrations.CreateModel(
            name='Reporte_cobros_acumulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('medio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Reporte Cobros Acumulados',
                'verbose_name': 'Reporte_cobros_acumulado',
            },
        ),
        migrations.CreateModel(
            name='Reporte_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('operadora', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Reporte Refunds',
                'verbose_name': 'Reporte_refund',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id_suscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11, unique=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Suscriptores',
                'verbose_name': 'Suscriptor',
            },
        ),
        migrations.CreateModel(
            name='Tipo_accion',
            fields=[
                ('tipo_accion', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_envio',
            fields=[
                ('id_tipo_envio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_envio', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo Envios',
                'verbose_name': 'Tipo_envio',
            },
        ),
        migrations.AddField(
            model_name='mensajes_informativo',
            name='tipo_accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Tipo_accion'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='tipo_accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Tipo_accion'),
        ),
        migrations.AddField(
            model_name='contenido_programado',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
        migrations.AddField(
            model_name='configuracion_broadcast',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
        migrations.AddField(
            model_name='configuracion_broadcast',
            name='id_tipo_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Tipo_envio'),
        ),
        migrations.AddField(
            model_name='club_suscriptor',
            name='suscriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Suscriptor'),
        ),
        migrations.AddField(
            model_name='club',
            name='id_pais_operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Pais_operadora'),
        ),
        migrations.AddField(
            model_name='club',
            name='id_plataforma_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Plataforma_envio'),
        ),
        migrations.AddField(
            model_name='base_cargada_broadcast',
            name='id_broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Configuracion_broadcast'),
        ),
        migrations.AddField(
            model_name='base_cargada_broadcast',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
        migrations.AddField(
            model_name='alta',
            name='club_suscriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club_suscriptor'),
        ),
    ]
