# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id_altas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('medio', models.CharField(max_length=20)),
                ('campania', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id_bajas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('medio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Base_cargada',
            fields=[
                ('id_base_cargada', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11)),
                ('fecha_envio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id_broadcast', models.AutoField(primary_key=True, serialize=False)),
                ('corto_envio', models.CharField(max_length=6)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('texto', models.CharField(max_length=160)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_club', models.CharField(max_length=20)),
                ('corto_mo_gratis', models.CharField(max_length=6)),
                ('corto_mt_gratis', models.CharField(max_length=6)),
                ('corto_mo_cobro', models.CharField(max_length=6)),
                ('corto_mt_cobro1', models.CharField(max_length=6)),
                ('corto_mt_cobro2', models.CharField(max_length=6)),
                ('corto_mt_cobro3', models.CharField(max_length=6)),
                ('corto_broadcast', models.CharField(max_length=6)),
                ('limite_envios_broadcast', models.PositiveIntegerField()),
                ('cantidad_cobros_diarios', models.PositiveSmallIntegerField()),
                ('puntos', models.PositiveIntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_suscriptor',
            fields=[
                ('id_club_suscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_primera_alta', models.DateTimeField()),
                ('fecha_ultimo_evento', models.DateTimeField()),
                ('fecha_ultimo_cobro', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('id_alta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Alta')),
                ('id_baja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Baja')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_envio',
            fields=[
                ('id_configuracion_envio', models.AutoField(primary_key=True, serialize=False)),
                ('hora_envio', models.TimeField()),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('fecha_ultimo_envio', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion_reenvio',
            fields=[
                ('id_configuracion_reenvio', models.AutoField(primary_key=True, serialize=False)),
                ('hora_envio', models.DateField()),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('fecha_ultimo_envio', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=200)),
                ('aleatorio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_programado',
            fields=[
                ('id_contenido_programado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('hora_envio', models.TimeField()),
                ('fecha_ejecucion', models.DateTimeField()),
                ('fecha_culminacion', models.DateTimeField()),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Conteo_recobro',
            fields=[
                ('id_conteo_recobro', models.AutoField(primary_key=True, serialize=False)),
                ('id_club', models.PositiveSmallIntegerField()),
                ('recobro', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dlr',
            fields=[
                ('id_dlr', models.AutoField(primary_key=True, serialize=False)),
                ('smsc_id', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=20)),
                ('dlr_to', models.CharField(max_length=100)),
                ('dlr_from', models.CharField(max_length=100)),
                ('dlr_ts', models.CharField(max_length=100)),
                ('id_sms', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id_edge', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('dlr_mask', models.CharField(max_length=200)),
                ('sms', models.CharField(max_length=20)),
                ('dlr_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envio_contenido',
            fields=[
                ('id_envio_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('id_sms', models.CharField(max_length=10)),
                ('cobro', models.PositiveSmallIntegerField()),
                ('msisdn', models.CharField(max_length=11)),
                ('fecha', models.DateTimeField()),
                ('corto', models.CharField(max_length=11)),
                ('recobro', models.PositiveSmallIntegerField()),
                ('id_contenido_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Contenido_programado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_envio',
            fields=[
                ('id_estado_envio', models.AutoField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_negra',
            fields=[
                ('id_lista_negra', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11, unique=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes_mo',
            fields=[
                ('id_mo', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=11)),
                ('destino', models.CharField(max_length=11)),
                ('mensaje', models.CharField(max_length=200)),
                ('binfo', models.CharField(max_length=6)),
                ('ruta', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id_operadora', models.AutoField(primary_key=True, serialize=False)),
                ('operadora', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20, unique=True)),
                ('prefijo', models.CharField(max_length=3)),
                ('moneda', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Pais_operadora',
            fields=[
                ('id_pais_operadora', models.AutoField(primary_key=True, serialize=False)),
                ('id_operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Operadora')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma_envio',
            fields=[
                ('id_plataforma_envio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_alta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('medio', models.CharField(max_length=20)),
                ('campania', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_baja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('medio', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_base_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('operadora', models.CharField(max_length=15)),
                ('usuarios_activos', models.IntegerField()),
                ('usuarios_baja', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('medio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_cobros_acumulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('medio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('corto', models.CharField(max_length=11)),
                ('operadora', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id_suscriptor', models.AutoField(primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=11)),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_envio',
            fields=[
                ('id_tipo_envio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_envio', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes_informativo',
            fields=[
                ('id_club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sms_api.Club')),
                ('bienvenida1', models.CharField(max_length=160)),
                ('bienvenida2', models.CharField(max_length=160)),
                ('salida', models.CharField(max_length=160)),
                ('ayuda', models.CharField(max_length=160)),
                ('ayuda_multiple', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='contenido_programado',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='id_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='configuracion_reenvio',
            name='id_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='configuracion_envio',
            name='id_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='club_suscriptor',
            name='id_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='club_suscriptor',
            name='id_suscriptor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Suscriptor'),
        ),
        migrations.AddField(
            model_name='club',
            name='id_pais_operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Pais_operadora'),
        ),
        migrations.AddField(
            model_name='club',
            name='id_plataforma_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Plataforma_envio'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='id_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='id_tipo_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Tipo_envio'),
        ),
        migrations.AddField(
            model_name='base_cargada',
            name='id_broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Broadcast'),
        ),
        migrations.AddField(
            model_name='base_cargada',
            name='id_estado_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Estado_envio'),
        ),
    ]
