# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='id_pais_operadora',
            new_name='pais_operadora',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='id_plataforma_envio',
            new_name='plataforma_envio',
        ),
    ]
