# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion_envio',
            name='hora_envio',
            field=models.TimeField(),
        ),
    ]
