# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0002_auto_20180615_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_accion',
            old_name='tipo_accion',
            new_name='nombre_accion',
        ),
    ]
