# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0003_auto_20180615_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alta',
            old_name='id_altas',
            new_name='id_alta',
        ),
        migrations.RenameField(
            model_name='baja',
            old_name='id_bajas',
            new_name='id_baja',
        ),
        migrations.RemoveField(
            model_name='baja',
            name='id_club',
        ),
        migrations.RemoveField(
            model_name='baja',
            name='id_suscriptor',
        ),
        migrations.AddField(
            model_name='baja',
            name='club_suscriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club_suscriptor'),
        ),
    ]
