# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0004_auto_20180615_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='corto_club',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
