# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0005_club_corto_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='id_club',
            new_name='club',
        ),
        migrations.AlterField(
            model_name='club',
            name='corto_club',
            field=models.CharField(max_length=6),
        ),
    ]
