# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0006_auto_20180618_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido_programado',
            old_name='id_contenido',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='contenido_programado',
            old_name='id_estado_envio',
            new_name='estado_envio',
        ),
    ]
