# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0008_auto_20180618_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edge',
            new_name='Configuracion_conexion_tigohn',
        ),
        migrations.AlterModelOptions(
            name='configuracion_conexion_tigohn',
            options={'verbose_name': 'Configuracion_conexion_tigohn', 'verbose_name_plural': 'Configuracion conexion tigohn'},
        ),
        migrations.RenameField(
            model_name='configuracion_conexion_tigohn',
            old_name='id_edge',
            new_name='id_conf',
        ),
    ]
