# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0009_auto_20180620_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion_conexion_tigohn',
            name='sms',
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='binfo',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club'),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='host',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='priority_c',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='priority_r',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='smsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='dlr_mask',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='dlr_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
