# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0010_auto_20180620_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion_conexion_tigohn',
            name='club',
        ),
        migrations.DeleteModel(
            name='Configuracion_conexion_tigohn',
        ),
    ]
