# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0011_auto_20180620_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_conexion_tigohn',
            fields=[
                ('id_conf', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('dlr_mask', models.CharField(max_length=200)),
                ('priority_c', models.CharField(max_length=2)),
                ('priority_r', models.CharField(max_length=2)),
                ('smsc', models.CharField(max_length=20)),
                ('dlr_url', models.CharField(max_length=100)),
                ('binfo', models.CharField(max_length=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Club')),
            ],
            options={
                'verbose_name': 'Configuracion_conexion_tigohn',
                'verbose_name_plural': 'Configuracion conexion tigohn',
            },
        ),
    ]
