# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0013_auto_20180620_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='binfo_c',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='configuracion_conexion_tigohn',
            name='binfo_r',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
