# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0014_auto_20180620_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='binfo_c',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='configuracion_conexion_tigohn',
            name='binfo_r',
            field=models.CharField(max_length=5),
        ),
    ]
