# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0016_auto_20180620_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio_contenido',
            old_name='id_sms',
            new_name='id_envio',
        ),
    ]
