# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0017_auto_20180620_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio_contenido',
            name='cobro',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='envio_contenido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
