# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0018_auto_20180621_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion_envio',
            old_name='id_club',
            new_name='club',
        ),
    ]
