# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0019_auto_20180621_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_suscriptor',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club_suscriptor',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
