# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0020_auto_20180621_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='contenido',
            new_name='texto',
        ),
    ]
