# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0021_auto_20180622_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_envio',
            old_name='estado_envio',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='contenido_programado',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido_programado',
            name='fecha_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
