# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0022_auto_20180622_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_envio',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
