# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0023_auto_20180622_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_programado',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido_programado',
            name='hora_envio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
