# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0024_auto_20180622_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion_reenvio',
            old_name='id_club',
            new_name='club',
        ),
        migrations.AlterField(
            model_name='contenido_programado',
            name='fecha_envio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contenido_programado',
            name='hora_envio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='conteo_recobro',
            name='recobro',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
