# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0025_auto_20180622_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_suscriptor',
            name='cantidad_cobro_diario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracion_envio',
            name='fecha_ultimo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion_reenvio',
            name='fecha_ultimo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
