# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0026_auto_20180622_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion_reenvio',
            name='hora_envio',
            field=models.TimeField(),
        ),
    ]
