# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0027_auto_20180622_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dlr',
            new_name='Dlr_tigo_hn',
        ),
    ]
