# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0028_auto_20180623_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlr_tigo_hn',
            old_name='id_sms',
            new_name='id_envio',
        ),
    ]
